version: '3.9'

services:
  money.api:
    image: ${DOCKER_REGISTRY-}money.api
    container_name: money.api
    environment:
        - ConnectionStrings__DefaultConnection=Host=money.postgres;Port=5432;Database=money;Username=postgres;Password=postgres; Include Error Detail=true
        - JwtOptions__Issuer=Money.API
        - JwtOptions__SecretKey=E54895EBEC1B8E100A1B6F55144A19272C3876FE9EB85C12377A4A2DE49282E8
    build:
      context: .
      dockerfile: ./Money.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
       - money.postgres
    
  money.postgres:
    image: postgres:latest
    container_name: money.postgres
    environment:
     - POSTGRES_DB=money
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - pgdata:/var/lib/postgresql/data
    ports:
    - 5433:5432
    
  pgadmin:
    container_name: money.pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mail.xyz
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
    pgdata:
    pgadmin-data:
